services:
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sara_site
      MYSQL_USER: user
      MYSQL_PASSWORD: zineb
    ports: ["3306:3306"]
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
